export const STORAGE_KEY  = {
  GLOBAL: 'CIDER:GLOBAL',
  AGI_PROVIDER_CONFIG_PREFIX: 'CIDER:AGI_PROVIDER:',
  AGI_PROVIDER_CONFIG_IDS: 'CIDER:AGI_PROVIDERS',
  CURRENT_AGI_PROVIDER_CONFIG_ID: 'CIDER:CURRENT_AGI_PROVIDER_CONFIG_ID',
  CHAT_HISTORY_LATEST_SESSION: 'CIDER:CHAT_HISTORY:LAST_SESSION',
  CHAT_HISTORY_PREFIX: 'CIDER:AGI_CHAT:'
}